name: ci

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
  norminette:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v6
       - uses: 42school/norminette@v3.3.51
         with:
          args: '-CheckForbiddenSourceHeader'

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: compile philo
        run: cp philo && make
      - name: run tests
        run: cp philo && make unit-tests
